[2023-06-09 22:27:05,578] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_inc_load_pipeline.load_sftp_data_data_11.csv manual__2023-06-09T22:03:08.195880+00:00 [queued]>
[2023-06-09 22:27:05,980] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_inc_load_pipeline.load_sftp_data_data_11.csv manual__2023-06-09T22:03:08.195880+00:00 [queued]>
[2023-06-09 22:27:05,985] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 22:27:05,986] {taskinstance.py:1242} INFO - Starting attempt 4 of 4
[2023-06-09 22:27:05,987] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 22:27:06,205] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_data_data_11.csv> on 2023-06-09 22:03:08.195880+00:00
[2023-06-09 22:27:06,274] {standard_task_runner.py:52} INFO - Started process 16991 to run task
[2023-06-09 22:27:06,326] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_inc_load_pipeline', 'load_sftp_data_data_11.csv', 'manual__2023-06-09T22:03:08.195880+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_inc_load_pipeline.py', '--cfg-path', '/tmp/tmpnok0iuas', '--error-file', '/tmp/tmpprj_x7q4']
[2023-06-09 22:27:06,387] {standard_task_runner.py:77} INFO - Job 260: Subtask load_sftp_data_data_11.csv
[2023-06-09 22:27:06,772] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_inc_load_pipeline.load_sftp_data_data_11.csv manual__2023-06-09T22:03:08.195880+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 22:27:07,379] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_inc_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_data_data_11.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T22:03:08.195880+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T22:03:08.195880+00:00
[2023-06-09 22:27:12,716] {logging_mixin.py:109} INFO - error while inserting to table: (psycopg2.errors.UndefinedColumn) column "ApptDate" of relation "leads_sftp" does not exist
LINE 1: ...DNUMBER", email_hash, phone_hash, "STATE", "ZIP", "ApptDate"...
                                                             ^

[SQL: INSERT INTO leads_sftp ("ENTRYDATE", "LEADNUMBER", email_hash, phone_hash, "STATE", "ZIP", "ApptDate", "Demo", "Set", "Dispo", "JobStatus", "CITY", loaded_at) VALUES (%(ENTRYDATE)s, %(LEADNUMBER)s, %(email_hash)s, %(phone_hash)s, %(STATE)s, %(ZIP)s, %(ApptDate)s, %(Demo)s, %(Set)s, %(Dispo)s, %(JobStatus)s, %(CITY)s, %(loaded_at)s)]
[parameters: ({'ENTRYDATE': '02-05-2023', 'LEADNUMBER': '289764', 'email_hash': '3b7c33e84ea3ae8b249dc1e1578fc84cb4047ac4', 'phone_hash': '6e5345441aaeb5816ee08728681bbb5e18cbf365', 'STATE': 'WA', 'ZIP': '98311', 'ApptDate': '', 'Demo': 'False', 'Set': '0', 'Dispo': 'Data', 'JobStatus': '', 'CITY': 'Bremerton                   ', 'loaded_at': '2023-06-09 22:26:43'}, {'ENTRYDATE': '12-17-2022', 'LEADNUMBER': '217893', 'email_hash': '137ac7f6012cc1165ccff9348abe55bb5fe86713', 'phone_hash': '8f2055fe6a78a8136b5e62e82d6b54b00d5c6ef9', 'STATE': 'AZ', 'ZIP': '85379', 'ApptDate': '01/02/2023  5:30PM', 'Demo': 'False', 'Set': '1', 'Dispo': 'CXL-BT', 'JobStatus': '', 'CITY': 'Surprise', 'loaded_at': '2023-06-09 22:26:43'}, {'ENTRYDATE': '12-15-2022', 'LEADNUMBER': '217597', 'email_hash': '77bd00d77b006ec1d92e855e8a480a78b4ac50b2', 'phone_hash': '262cf77e45bd889545b902eae7d21284b53e3dbc', 'STATE': 'WA', 'ZIP': '98346', 'ApptDate': '', 'Demo': 'False', 'Set': '0', 'Dispo': 'Data', 'JobStatus': '', 'CITY': 'Kingston', 'loaded_at': '2023-06-09 22:26:43'}, {'ENTRYDATE': '01-02-2023', 'LEADNUMBER': '221289', 'email_hash': 'b417026cce185454e4a1bd493b0846f503d95d17', 'phone_hash': 'f5a06e81bf514b38e5e5ffc3c4ba0c3ff4e65adf', 'STATE': 'OR', 'ZIP': '97146', 'ApptDate': '', 'Demo': 'False', 'Set': '0', 'Dispo': 'Data', 'JobStatus': '', 'CITY': 'Warrenton', 'loaded_at': '2023-06-09 22:26:43'}, {'ENTRYDATE': '02-22-2023', 'LEADNUMBER': '295200', 'email_hash': '9ace8905ba40aa18db1085b0b9423e5637d82f7b', 'phone_hash': 'dcc6dc12d351803a5aa0b363425609a8a2f31fbb', 'STATE': 'NV', 'ZIP': '89145', 'ApptDate': '', 'Demo': 'False', 'Set': '0', 'Dispo': 'Data', 'JobStatus': '', 'CITY': 'Las Vegas', 'loaded_at': '2023-06-09 22:26:43'}, {'ENTRYDATE': '12-01-2022', 'LEADNUMBER': '214121', 'email_hash': '91bf175bba539940351d41ea61cb153ceca488d7', 'phone_hash': 'a6580457df3c4105077f1fb54c4189d623c8ff9d', 'STATE': 'NV', 'ZIP': '89156', 'ApptDate': '', 'Demo': 'False', 'Set': '0', 'Dispo': 'Data', 'JobStatus': '', 'CITY': 'Las Vegas', 'loaded_at': '2023-06-09 22:26:43'}, {'ENTRYDATE': '12-08-2022', 'LEADNUMBER': '215843', 'email_hash': 'f5436a04877387a2264aa40126a5fa0d631241a0', 'phone_hash': 'c9162f8021288f162c4ce847eeef5c6f749f670d', 'STATE': 'WA', 'ZIP': '98075', 'ApptDate': '12/09/2022  9:00AM', 'Demo': 'True', 'Set': '1', 'Dispo': 'DNS-Pro', 'JobStatus': '', 'CITY': 'Sammamish', 'loaded_at': '2023-06-09 22:26:43'}, {'ENTRYDATE': '01-19-2023', 'LEADNUMBER': '225676', 'email_hash': 'f50e67e141081752a5f6e4bfa48d46e21cbb1c2d', 'phone_hash': '846dc45fa9f76ffa8faa7c4ce2eca895c26bc462', 'STATE': 'AZ', 'ZIP': '85345', 'ApptDate': '', 'Demo': 'False', 'Set': '0', 'Dispo': 'DQ-Bought Comp', 'JobStatus': '', 'CITY': 'Peoria', 'loaded_at': '2023-06-09 22:26:43'}  ... displaying 10 of 3709 total bound parameter sets ...  {'ENTRYDATE': '03-06-2023', 'LEADNUMBER': '298848', 'email_hash': 'f5e7dcb53b1a1efd0e59a20eee5737a88f6fb636', 'phone_hash': '6ca904d6be88d4d97bcca6e2572ca0cc358f91d5', 'STATE': 'WA', 'ZIP': '98597', 'ApptDate': '', 'Demo': 'False', 'Set': '0', 'Dispo': 'DQ-Build a Home', 'JobStatus': '', 'CITY': 'Yelm', 'loaded_at': '2023-06-09 22:26:43'}, {'ENTRYDATE': '01-30-2023', 'LEADNUMBER': '227931', 'email_hash': '2f0fa54d71d7d2fbcef3a0850d85a1d5f83bab67', 'phone_hash': '9ef11a6a337abdf924dbec0e8874f88c77c7f701', 'STATE': 'NV', 'ZIP': '89130', 'ApptDate': '', 'Demo': 'False', 'Set': '0', 'Dispo': 'Data', 'JobStatus': '', 'CITY': 'Las Vegas', 'loaded_at': '2023-06-09 22:26:43'})]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2023-06-09 22:27:13,032] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 22:27:13,122] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_inc_load_pipeline, task_id=load_sftp_data_data_11.csv, execution_date=20230609T220308, start_date=20230609T222705, end_date=20230609T222713
[2023-06-09 22:27:13,723] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
