[2023-06-09 15:08:33,165] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_2.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:33,389] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_2.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 15:08:33,395] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:33,408] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:08:33,409] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:08:33,489] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_2.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 15:08:33,513] {standard_task_runner.py:52} INFO - Started process 1483 to run task
[2023-06-09 15:08:33,538] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_2.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmppbv_bbpi', '--error-file', '/tmp/tmpi5uq8kft']
[2023-06-09 15:08:33,559] {standard_task_runner.py:77} INFO - Job 26: Subtask load_sftp_datadata_2.csv
[2023-06-09 15:08:33,797] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_2.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:08:34,190] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_2.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 15:08:34,263] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:08:34,358] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:08:34,544] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_2.csv, execution_date=20230608T000000, start_date=20230609T150833, end_date=20230609T150834
[2023-06-09 15:08:38,488] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 15:22:20,024] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_2.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:20,332] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_2.csv manual__2023-06-09T15:20:24.730543+00:00 [queued]>
[2023-06-09 15:22:20,342] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:20,343] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 15:22:20,344] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 15:22:20,742] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_2.csv> on 2023-06-09 15:20:24.730543+00:00
[2023-06-09 15:22:20,829] {standard_task_runner.py:52} INFO - Started process 3525 to run task
[2023-06-09 15:22:20,912] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_2.csv', 'manual__2023-06-09T15:20:24.730543+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmp58nu_a20', '--error-file', '/tmp/tmpua4zpvyn']
[2023-06-09 15:22:20,923] {standard_task_runner.py:77} INFO - Job 77: Subtask load_sftp_datadata_2.csv
[2023-06-09 15:22:21,197] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_2.csv manual__2023-06-09T15:20:24.730543+00:00 [running]> on host 8cb5811d1998
[2023-06-09 15:22:22,012] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_2.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T15:20:24.730543+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T15:20:24.730543+00:00
[2023-06-09 15:22:22,169] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '../data/temp_files/None'
[2023-06-09 15:22:22,560] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 15:22:22,891] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_2.csv, execution_date=20230609T152024, start_date=20230609T152220, end_date=20230609T152222
[2023-06-09 15:22:23,517] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-09 16:52:34,251] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_2.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:34,592] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_2.csv scheduled__2023-06-08T00:00:00+00:00 [queued]>
[2023-06-09 16:52:34,596] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:34,598] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-06-09 16:52:34,598] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 16:52:34,937] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_sftp_datadata_2.csv> on 2023-06-08 00:00:00+00:00
[2023-06-09 16:52:34,977] {standard_task_runner.py:52} INFO - Started process 850 to run task
[2023-06-09 16:52:35,016] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'sftp_raw_data_full_load_pipeline', 'load_sftp_datadata_2.csv', 'scheduled__2023-06-08T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/sftp_raw_data_full_load_pipeline.py', '--cfg-path', '/tmp/tmpf94ls9ie', '--error-file', '/tmp/tmpjs2ncoe8']
[2023-06-09 16:52:35,102] {standard_task_runner.py:77} INFO - Job 33: Subtask load_sftp_datadata_2.csv
[2023-06-09 16:52:35,648] {logging_mixin.py:109} INFO - Running <TaskInstance: sftp_raw_data_full_load_pipeline.load_sftp_datadata_2.csv scheduled__2023-06-08T00:00:00+00:00 [running]> on host 6ba608d2de6e
[2023-06-09 16:52:36,140] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=Hassan@gmail.com
AIRFLOW_CTX_DAG_OWNER=Hassan
AIRFLOW_CTX_DAG_ID=sftp_raw_data_full_load_pipeline
AIRFLOW_CTX_TASK_ID=load_sftp_datadata_2.csv
AIRFLOW_CTX_EXECUTION_DATE=2023-06-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-08T00:00:00+00:00
[2023-06-09 16:52:36,262] {logging_mixin.py:109} INFO - error while inserting to table: [Errno 2] No such file or directory: '/opt/data/temp_files/None'
[2023-06-09 16:52:36,687] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-06-09 16:52:37,156] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=sftp_raw_data_full_load_pipeline, task_id=load_sftp_datadata_2.csv, execution_date=20230608T000000, start_date=20230609T165234, end_date=20230609T165237
[2023-06-09 16:52:40,930] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
